### ISSUE TITLE
Problem with project file meta data not in project directory

### ISSUE THREAD

**Issue by ioniks** [junichi11/netbeans-gitignore-io-plugin#2]
When i create a project with project meta data in another directory, the .gitignore is placed in project meta data directory not in project directory.

**Comment by junichi11** [comment]
I guess that you are using a php project. Unfortunately, a meta data directory means project directory.
Your php application directory is called source directory.

I'll add a FileChooser to the dialog to set a directory path.

Thanks.

**Comment by ioniks** [comment]
Thanks :)

**Comment by junichi11** [comment]
@ioniks 
Done. Please try to use it. 
https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.1.4

Thanks.

**Comment by ioniks** [comment]
Yes i have a directory to say for it.

I have prefered a choice for source or metadata directory but it's good :)

**Comment by junichi11** [comment]
> I have prefered a choice for source or metadata directory

Unfortunately, we can't do it because this plugin has to support all project type. A PHP project has a source directory but another project type may not have it. And we can't get a source directory using project api.
