### ISSUE TITLE
Plugin nbm does not contain plugin description

### ISSUE THREAD

**Issue by bondolo** [junichi11/netbeans-gitignore-io-plugin#4]
The nbm distributable does not contain any description metadata. This means when viewing the plugin on NetBeans update centre it is unclear what the plugin does. The provided link does go to the github site which does provide a reasonable description from the README.md

Please add a description to the "OpenIDE-Module-Short-Description", perhaps just the contents of the README.

**Comment by junichi11** [comment]
I'll do that later. 

Thanks.

**Comment by junichi11** [comment]
I'm sorry to be late. Fixed.

Thanks.
