### ISSUE TITLE
gitignore.io/api/list change breaks available ignore types

### ISSUE THREAD

**Issue by baykant** [junichi11/netbeans-gitignore-io-plugin#5]
Hi,

I am using this plugin in netbeans 8.2 (used it for 8.1, 8 and previous versions also for more than 1 year)

Recently gitignore.io/api/list output format changed and comma (,) from the line ends removed. The available type list could not split output correctly 
Current gitignore.io/api/list output sample below:  
`momentics,monodevelop,nanoc,ncrunch,nesc`  
`netbeans,nette,nim,ninja,node`

The result of this output populates list with combined type list like **nescnetbeans**  
After I created an issue for this change in https://github.com/joeblau/gitignore.io 
( https://github.com/joeblau/gitignore.io/issues/299 ) I got a response that now there are 2 more output types, lines and json format.  

I guess GITIGNORE_API_LIST and / or splitGitIgnores() method in GitIgnoreListPanel.java may be updated for fixing this issue. 

sample selection dialog screenshot is attached.
![gitignore io available list_044](https://cloud.githubusercontent.com/assets/23583936/22862127/55a0e6c2-f131-11e6-9e3f-4ddc55d532a3.png)

**Comment by junichi11** [comment]
Thanks for reporting it! I'll fix it.

**Comment by junichi11** [comment]
Fixed. Please try to use the new version (0.3.0). 

https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.3.0

Thanks.

**Comment by junichi11** [comment]
@baykant BTW, if you tried it, please let me know. Because I would like to upload the nbm to the Plugin Portal if there are no problems.

Thanks.

**Comment by baykant** [comment]
@junichi11 I just downloaded and tried. Working without any issue for now. Thanks for the update.

**Comment by junichi11** [comment]
@baykant Thank you for the quick testing :)
